spring:
  application:
    name: ${APPNAME_STOK_SERVICE:stok-service}
  datasource:
    password: password
    url: jdbc:postgresql://${POSTGRES_STOK_HOST}:${POSTGRES_STOK_PORT}/stok
    username: marul
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: ${STOK_SERVICE_PORT:8088}
  servlet:
    context-path: /${APPNAME_STOK_SERVICE:stok-service}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST:localhost}:${SERVICE_DISCOVERY_PORT:8761}/eureka
  instance:
    hostname: ${STOK_SERVICE_HOST}
#    prefer-ip-address: true

