eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
server:
  port: ${SERVICE_DISCOVERY_PORT:8761}
spring:
  application:
    name: ${APPNAME_SERVICE_DISCOVERY:service-discovery}