server:
  port: ${MAIL_SERVER_PORT:8083}
  servlet:
    context-path: /${APPNAME_MAIL_SERVICE:mail-service}
spring:
  application:
    name: ${APPNAME_MAIL_SERVICE:mail-service}

  mail:
    host: smtp.gmail.com
    port: 587
    username: com.tr.marul@gmail.com
    password: ***************
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${APPNAME_SERVICE_DISCOVERY}:${SERVICE_DISCOVERY_PORT}/eureka
  instance:
    hostname: ${APPNAME_SERVICE_DISCOVERY}

email-sender:
  basariliMesaj: Email başarıyla gönderildi
  basarisizMesaj: Email gönderirken hata
  ekAdi: rapor.pdf
