server:
  port: ${MAIL_SERVER_PORT:8083}
  servlet:
    context-path: /${APPNAME_MAIL_SERVICE:mail-service}
spring:
  application:
    name: ${APPNAME_MAIL_SERVICE:mail-service}
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER}
  mail:
    host: smtp.gmail.com
    port: 587
    username: organik.marul.tk@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST:localhost}:${SERVICE_DISCOVERY_PORT:8761}/eureka
  instance:
    hostname: ${MAIL_SERVICE_HOST}
    prefer-ip-address: true

mail-properties:
  basariliMesaj: Email başarıyla gönderildi
  basarisizMesaj: Email gönderirken hata
  ekAdi: rapor.pdf
  adSoyad: '${AD_SOYAD:Hüseyin Kaan Kızıldağ}'
  from: com.tr.marul@gmail.com
