server:
  port: ${SATIS_SERVICE_PORT:8086}
  servlet:
    context-path: /${APPNAME_SATIS_SERVICE}
spring:
  application:
    name: ${APPNAME_SATIS_SERVICE:satis-service}
  datasource:
    password: password
    url: jdbc:postgresql://${POSTGRES_SATIS_HOST}:${POSTGRES_SATIS_PORT}/satis
    username: marul
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST:localhost}:${SERVICE_DISCOVERY_PORT:8761}/eureka
  instance:
    hostname: ${SATIS_SERVICE_HOST}