server:
  port: ${SATIS_SERVICE_PORT:8086}
  servlet:
    context-path: /${APPNAME_SATIS_SERVICE}
spring:
  application:
    name: ${APPNAME_SATIS_SERVICE:satis-service}
  datasource:
    password: password
    url: jdbc:postgresql://${POSTGRES_SATIS_HOST}:${POSTGRES_SATIS_PORT}/satis
    username: marul
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true