version: '3.7'
services:
  postgres-musteri:
    container_name: postgres-musteri
    build:
      context: database/musteri_database
      dockerfile: /Dockerfile
    environment:
      POSTGRES_USER: marul
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres_musteri:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  postgres-stok:
    container_name: postgres-stok
    build:
      context: database/stok_database
      dockerfile: /Dockerfile
    environment:
      POSTGRES_USER: marul
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres_stok:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-satis:
    container_name: postgres-satis
    build:
      context: database/satis_database
      dockerfile: /Dockerfile
    environment:
      POSTGRES_USER: marul
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres_satis:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres

  musteri-service:
    container_name: musteri-service
    image: marul/musteri-service
    build:
      context: ../musteri-service
      dockerfile: ../musteri-service/Dockerfile
    #    volumes:
    #      - ./wait-for-it.sh/:/usr/share/wait-for-it.sh
    ports:
      - "${MUSTERI_SERVICE_PORT}:${MUSTERI_SERVICE_PORT}"
    environment:
      - APPNAME_MUSTERI_SERVICE=${APPNAME_MUSTERI_SERVICE}
      - MUSTERI_SERVICE_PORT=${MUSTERI_SERVICE_PORT}
      - POSTGRES_MUSTERI_PORT=${POSTGRES_MUSTERI_PORT}
      - POSTGRES_MUSTERI_HOST=${POSTGRES_MUSTERI_HOST}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
      - SERVICE_DISCOVERY_PORT=${SERVICE_DISCOVERY_PORT}
      - APPNAME_SERVICE_DISCOVERY=${APPNAME_SERVICE_DISCOVERY}
      - MUSTERI_SERVICE_HOST=${MUSTERI_SERVICE_HOST}
      - SERVICE_DISCOVERY_HOST=${SERVICE_DISCOVERY_HOST}
    depends_on:
      - postgres-musteri
    networks:
      - postgres
      - spring

  mail-service:
    container_name: mail-service
    image: marul/mail-service
    build:
      context: ../mail-service
      dockerfile: ../mail-service/Dockerfile
    ports:
      - "${MAIL_SERVICE_PORT}:${MAIL_SERVICE_PORT}"
    environment:
      - SERVICE_DISCOVERY_PORT=${SERVICE_DISCOVERY_PORT}
      - APPNAME_SERVICE_DISCOVERY=${APPNAME_SERVICE_DISCOVERY}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - SERVICE_DISCOVERY_HOST=${SERVICE_DISCOVERY_HOST}
      - MAIL_SERVICE_PORT=${MAIL_SERVICE_PORT}
      - MAIL_SERVICE_HOST=${MAIL_SERVICE_HOST}
      - BOOTSTRAP_SERVER=${BOOTSTRAP_SERVER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    networks:
      - spring
      - kafka

  api-gateway:
    container_name: api-gateway
    image: marul/api-gateway
    build:
      context: ../api-gateway-service
      dockerfile: ../api-gateway-service/Dockerfile
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      - SERVICE_DISCOVERY_PORT=${SERVICE_DISCOVERY_PORT}
      - APPNAME_SERVICE_DISCOVERY=${APPNAME_SERVICE_DISCOVERY}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - APPNAME_MUSTERI_SERVICE=${APPNAME_MUSTERI_SERVICE}
      - APPNAME_API_GATEWAY=${APPNAME_API_GATEWAY}
      - APPNAME_RAPOR_SERVICE=${APPNAME_RAPOR_SERVICE}
      - APPNAME_MAIL_SERVICE=${APPNAME_MAIL_SERVICE}
      - APPNAME_SATIS_SERVICE=${APPNAME_SATIS_SERVICE}
      - APPNAME_STOK_SERVICE=${APPNAME_STOK_SERVICE}
      - SERVICE_DISCOVERY_HOST=${SERVICE_DISCOVERY_HOST}
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - API_GATEWAY_HOST=${API_GATEWAY_HOST}
    networks:
      - spring

  service-discovery:
    container_name: service-discovery
    image: marul/service-discovery
    build:
      context: ../service-discovery
      dockerfile: ../service-discovery/Dockerfile
    ports:
      - "${SERVICE_DISCOVERY_PORT}:${SERVICE_DISCOVERY_PORT}"
    environment:
      - SERVICE_DISCOVERY_PORT=${SERVICE_DISCOVERY_PORT}
      - APPNAME_SERVICE_DISCOVERY=${APPNAME_SERVICE_DISCOVERY}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - SERVICE_DISCOVERY_HOST=${SERVICE_DISCOVERY_HOST}
    networks:
      - spring

  rapor-service:
    container_name: rapor-service
    image: marul/rapor-service
    build:
      context: ../rapor-service
      dockerfile: ../rapor-service/Dockerfile
    ports:
      - "${RAPOR_SERVICE_PORT}:${RAPOR_SERVICE_PORT}"
    environment:
      - LOGSTASH_PORT=${LOGSTASH_PORT}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - APPNAME_SERVICE_DISCOVERY=${APPNAME_SERVICE_DISCOVERY}
      - RAPORLAR_DIZINI=${RAPORLAR_DIZINI}
      - SERVICE_DISCOVERY_PORT=${SERVICE_DISCOVERY_PORT}
      - MARUL_LOGO_PATH=${MARUL_LOGO_PATH}
      - SERVICE_DISCOVERY_HOST=${SERVICE_DISCOVERY_HOST}
      - RAPOR_SERVICE_HOST=${RAPOR_SERVICE_HOST}
      - RAPOR_SERVICE_PORT=${RAPOR_SERVICE_PORT}
    networks:
      - postgres
      - spring

  stok-service:
    container_name: stok-service
    image: marul/stok-service
    build:
      context: ../stok-service
      dockerfile: ../stok-service/Dockerfile
    #    volumes:
    #      - ./wait-for-it.sh/:/usr/share/wait-for-it.sh
    ports:
      - "${STOK_SERVICE_PORT}:${STOK_SERVICE_PORT}"
    environment:
      - APPNAME_STOK_SERVICE=${APPNAME_STOK_SERVICE}
      - STOK_SERVICE_PORT=${STOK_SERVICE_PORT}
      - POSTGRES_STOK_PORT=${POSTGRES_STOK_PORT}
      - POSTGRES_STOK_HOST=${POSTGRES_STOK_HOST}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
      - SERVICE_DISCOVERY_PORT=${SERVICE_DISCOVERY_PORT}
      - APPNAME_SERVICE_DISCOVERY=${APPNAME_SERVICE_DISCOVERY}
      - STOK_SERVICE_HOST=${STOK_SERVICE_HOST}
      - SERVICE_DISCOVERY_HOST=${SERVICE_DISCOVERY_HOST}
    depends_on:
      - postgres-stok
    networks:
      - postgres
      - spring

  satis-service:
    container_name: satis-service
    image: marul/satis-service
    build:
      context: ../satis-service
      dockerfile: ../satis-service/Dockerfile
    #    volumes:
    #      - ./wait-for-it.sh/:/usr/share/wait-for-it.sh
    ports:
      - "${SATIS_SERVICE_PORT}:${SATIS_SERVICE_PORT}"
    environment:
      - APPNAME_SATIS_SERVICE=${APPNAME_SATIS_SERVICE}
      - SATIS_SERVICE_PORT=${SATIS_SERVICE_PORT}
      - POSTGRES_SATIS_PORT=${POSTGRES_SATIS_PORT}
      - POSTGRES_SATIS_HOST=${POSTGRES_SATIS_HOST}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=${LOGSTASH_PORT}
      - SERVICE_DISCOVERY_PORT=${SERVICE_DISCOVERY_PORT}
      - APPNAME_SERVICE_DISCOVERY=${APPNAME_SERVICE_DISCOVERY}
      - SATIS_SERVICE_HOST=${SATIS_SERVICE_HOST}
      - SERVICE_DISCOVERY_HOST=${SERVICE_DISCOVERY_HOST}
      - BOOTSTRAP_SERVER=${BOOTSTRAP_SERVER}
    depends_on:
      - postgres-satis
    networks:
      - postgres
      - spring
      - kafka
  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://${BOOTSTRAP_SERVER}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - kafka

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
  kafka:
    driver: bridge

volumes:
  postgres_musteri:
  postgres_satis:
  postgres_stok:
  pgadmin:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local