version: '3.7'
services:
  elastic-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: elastic-1
    environment:
      - node.name=elastic-1
      - cluster.name=tts-ms-elastic-cluster
      - discovery.seed_hosts=elastic-2
      - cluster.initial_master_nodes=elastic-1,elastic-2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticData01:/var/lib/elasticsearch/data
    ports:
      - "9200:${ELASTIC_PORT}"
      - "9300:9300"
    networks:
      - ${GLOBAL_NETWORK:-elk}

  elastic-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: elastic-2
    environment:
      - node.name=elastic-2
      - cluster.name=tts-ms-elastic-cluster
      - discovery.seed_hosts=elastic-1
      - cluster.initial_master_nodes=elastic-1,elastic-2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticData02:/var/lib/elasticsearch/data
    ports:
      - "9201:${ELASTIC_PORT}"
      - "9301:9300"
    networks:
      - ${GLOBAL_NETWORK:-elk}

  kibana:
    image: kibana:${ELK_VERSION}
    container_name: kibana
    restart: always
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
    environment:
      - ELASTICSEARCH_URL=http://elastic-1:${ELASTIC_PORT}
      - ELASTICSEARCH_HOSTS=["http://elastic-1:${ELASTIC_PORT}","http://elastic-2:${ELASTIC_PORT}"]
    depends_on:
      - elastic-1
      - elastic-2
      - logstash
    networks:
      - ${GLOBAL_NETWORK:-elk}

  logstash:
    image: logstash:${ELK_VERSION}
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf/:/usr/share/logstash/pipeline/logstash.conf
      - ./wait-for-it.sh/:/usr/share/wait-for-it.sh
    command: bash -c "/usr/share/wait-for-it.sh -h elastic-1 -p ${ELASTIC_PORT} -t 120
      && logstash -f /usr/share/logstash/pipeline/logstash.conf"
    depends_on:
      - elastic-1
      - elastic-2
    ports:
      - "${LOGSTASH_PORT}:${LOGSTASH_PORT}"
    environment:
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - ${GLOBAL_NETWORK:-elk}

volumes:
  elasticData01:
    driver: local
  elasticData02:
    driver: local
