eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST:localhost}:${SERVICE_DISCOVERY_PORT:8761}/eureka
  instance:
    hostname: ${MUSTERI_SERVICE_HOST}
server:
  port: ${MUSTERI_SERVICE_PORT:8080}
  servlet:
    context-path: /${APPNAME_MUSTERI_SERVICE:musteri-service}

spring:
  application:
    name: ${APPNAME_MUSTERI_SERVICE:musteri-service}
  datasource:
    password: password
    url: jdbc:postgresql://${POSTGRES_MUSTERI_HOST}:${POSTGRES_MUSTERI_PORT}/musteri
    username: marul
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true