eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${APPNAME_SERVICE_DISCOVERY}:${SERVICE_DISCOVERY_PORT}/eureka
  instance:
    hostname: ${spring.application.name}
server:
  port: ${RAPOR_SERVICE_PORT:8081}
  servlet:
    context-path: /${APPNAME_RAPOR_SERVICE:rapor-service}
spring:
  application:
    name: ${APPNAME_RAPOR_SERVICE:rapor-service}


rapor-service:
  raporlar_dizini: ${RAPORLAR_DIZINI}