eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST:localhost}:${SERVICE_DISCOVERY_PORT:8761}/eureka
  instance:
    hostname: ${RAPOR_SERVICE_HOST}
server:
  port: ${RAPOR_SERVICE_PORT:8081}
  servlet:
    context-path: /${APPNAME_RAPOR_SERVICE:rapor-service}
spring:
  application:
    name: ${APPNAME_RAPOR_SERVICE:rapor-service}


rapor-service:
  raporlar_dizini: ${RAPORLAR_DIZINI}