server:
  port: '${API_GATEWAY_PORT:8084}'
spring:
  application:
    name: ${APPNAME_API_GATEWAY}

eureka:
  instance:
    hostname: ${APPNAME_SERVICE_DISCOVERY}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${APPNAME_SERVICE_DISCOVERY}:${SERVICE_DISCOVERY_PORT}/eureka


resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 1
      permittedNumberOfCallsInHalfOpenState: 2

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 10s


