server:
  port: '${API_GATEWAY_PORT:8084}'
spring:
  application:
    name: ${APPNAME_API_GATEWAY}
  cloud:
    gateway:
      routes:
        - id: ${APPNAME_MUSTERI_SERVICE}
          uri: lb://${APPNAME_MUSTERI_SERVICE}
          predicates:
            - Path=/${APPNAME_MUSTERI_SERVICE}/**
          filters:
            - name: CircuitBreaker
              args:
                name: circuit-breaker
                fallbackUri: forward://${APPNAME_API_GATEWAY}/v1/api-gateway/common-fallback
        - id: ${APPNAME_RAPOR_SERVICE}
          uri: lb://${APPNAME_RAPOR_SERVICE}
          predicates:
            - Path=/${APPNAME_RAPOR_SERVICE}/**
          filters:
            - name: CircuitBreaker
              args:
                name: circuit-breaker
                fallbackUri: forward://${APPNAME_API_GATEWAY}/v1/api-gateway/common-fallback
        - id: ${APPNAME_MAIL_SERVICE}
          uri: lb://${APPNAME_MAIL_SERVICE}
          predicates:
            - Path=/${APPNAME_MAIL_SERVICE}/**
          filters:
            - name: CircuitBreaker
              args:
                name: circuit-breaker
                fallbackUri: forward://${APPNAME_API_GATEWAY}/v1/api-gateway/common-fallback
        - id: ${APPNAME_STOK_SERVICE}
          uri: lb://${APPNAME_STOK_SERVICE}
          predicates:
            - Path=/${APPNAME_STOK_SERVICE}/**
          filters:
            - name: CircuitBreaker
              args:
                name: circuit-breaker
                fallbackUri: forward://${APPNAME_API_GATEWAY}/v1/api-gateway/common-fallback
        - id: ${APPNAME_SATIS_SERVICE}
          uri: lb://${APPNAME_SATIS_SERVICE}
          predicates:
            - Path=/${APPNAME_SATIS_SERVICE}/**
          filters:
            - name: CircuitBreaker
              args:
                name: circuit-breaker
                fallbackUri: forward://${APPNAME_API_GATEWAY}/v1/api-gateway/common-fallback

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
eureka:
  instance:
    hostname: ${API_GATEWAY_HOST}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST:localhost}:${SERVICE_DISCOVERY_PORT:8761}/eureka


resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 1
      permittedNumberOfCallsInHalfOpenState: 2

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 10s

